#!/usr/bin/env python3

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet
import os
import argparse

def make_report(output_pdf, image_dir):
    # Set up document
    doc = SimpleDocTemplate(output_pdf, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()

    # Header details
    story.append(Paragraph(f"<b>Spectra pipeline output report:</b> The following figures were auto-generated by the Spectra pipeline. These figures show the relationship between kmers in raw sequence data and in a genome assembly.", styles["Normal"]))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph(f"<b>Page 1: </b> The following figures were auto-generated by the Spectra pipeline. These figures show the relationship between kmers in raw sequence data and in a genome assembly.", styles["Normal"]))


    # Walk through images
    for fname in sorted(os.listdir(image_dir)):
        if fname.lower().endswith((".png", ".jpg", ".jpeg")):
            img_path = os.path.join(image_dir, fname)

            # Add image with scaling
            img = Image(img_path)
            img._restrictSize(6 * inch, 8 * inch)  # scale to fit page
            story.append(img)
            story.append(Spacer(1, 0.2 * inch))
            story.append(Paragraph(fname, styles["Italic"]))
            story.append(PageBreak())

    # Build PDF
    doc.build(story)

# CLI arguments
parser = argparse.ArgumentParser(description='Spectra pipeline report writer')
parser.add_argument('-i', '--image-directory', dest='directory', type=str, help='Input image directory', required=True)
parser.add_argument('-o', '--output', dest='output', type=str, help='Output pdf filename', default='spectra_report.pdf')
parser.add_argument('-m', '--mer-size', dest='mer_size', type=int, help='kmer size to tabulate.', default=3)
args=parser.parse_args()

make_report(output_pdf=args.output,image_dir=args.directory)
